2025-07-26 16:09:49,818 - ERROR - 
        Error in [C:\Users\harsh\OneDrive\Desktop\Harshita\LLMOpsCourse\document_portal\exception\custom_exception.py] at line [24]
        Message: division by zero
        Traceback:
        Traceback (most recent call last):
  File "C:\Users\harsh\OneDrive\Desktop\Harshita\LLMOpsCourse\document_portal\exception\custom_exception.py", line 24, in <module>
    a = 1 / 0
ZeroDivisionError: division by zero

        
